version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_KAFKA_LOG_DIRS=/var/lib/kafka/data

  # Add additional services for your Kafka clients, e.g., producers or consumers

networks:
  default:
    name: kafka